name: Node.js CI

on:
  push:
    branches: [ "main" ]
    paths-ignore: 
        - 'train-tracker/src/backend/**'
    
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.11.0
      uses: actions/setup-node@v4
      with:
        cache-dependency-path: train-tracker/package-lock.json
        node-version: 22.11.0
        cache: 'npm'
    - run: npm ci
      working-directory: train-tracker
    - run: npm run build --if-present
      working-directory: train-tracker
      env: 
        CI: false
    - name: Deploy with gh-pages
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      working-directory: train-tracker
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CI: false
